# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from bbthings_grpc.proto.resource import data_pb2 as bbthings__grpc_dot_proto_dot_resource_dot_data__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in bbthings_grpc/proto/resource/data_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReadData = channel.unary_unary(
                '/data.DataService/ReadData',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataTime.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataReadResponse.FromString,
                _registered_method=True)
        self.ListDataByTime = channel.unary_unary(
                '/data.DataService/ListDataByTime',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataTime.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataListResponse.FromString,
                _registered_method=True)
        self.ListDataByEarlier = channel.unary_unary(
                '/data.DataService/ListDataByEarlier',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataEarlier.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataListResponse.FromString,
                _registered_method=True)
        self.ListDataByLater = channel.unary_unary(
                '/data.DataService/ListDataByLater',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataLater.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataListResponse.FromString,
                _registered_method=True)
        self.ListDataByRange = channel.unary_unary(
                '/data.DataService/ListDataByRange',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataRange.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataListResponse.FromString,
                _registered_method=True)
        self.ListDataByNumberBefore = channel.unary_unary(
                '/data.DataService/ListDataByNumberBefore',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataNumber.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataListResponse.FromString,
                _registered_method=True)
        self.ListDataByNumberAfter = channel.unary_unary(
                '/data.DataService/ListDataByNumberAfter',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataNumber.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataListResponse.FromString,
                _registered_method=True)
        self.ListDataGroupByTime = channel.unary_unary(
                '/data.DataService/ListDataGroupByTime',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataGroupTime.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataListResponse.FromString,
                _registered_method=True)
        self.ListDataGroupByEarlier = channel.unary_unary(
                '/data.DataService/ListDataGroupByEarlier',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataGroupEarlier.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataListResponse.FromString,
                _registered_method=True)
        self.ListDataGroupByLater = channel.unary_unary(
                '/data.DataService/ListDataGroupByLater',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataGroupLater.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataListResponse.FromString,
                _registered_method=True)
        self.ListDataGroupByRange = channel.unary_unary(
                '/data.DataService/ListDataGroupByRange',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataGroupRange.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataListResponse.FromString,
                _registered_method=True)
        self.ListDataGroupByNumberBefore = channel.unary_unary(
                '/data.DataService/ListDataGroupByNumberBefore',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataGroupNumber.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataListResponse.FromString,
                _registered_method=True)
        self.ListDataGroupByNumberAfter = channel.unary_unary(
                '/data.DataService/ListDataGroupByNumberAfter',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataGroupNumber.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataListResponse.FromString,
                _registered_method=True)
        self.ReadDataSet = channel.unary_unary(
                '/data.DataService/ReadDataSet',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataSetTime.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataSetReadResponse.FromString,
                _registered_method=True)
        self.ListDataSetByTime = channel.unary_unary(
                '/data.DataService/ListDataSetByTime',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataSetTime.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataSetListResponse.FromString,
                _registered_method=True)
        self.ListDataSetByEarlier = channel.unary_unary(
                '/data.DataService/ListDataSetByEarlier',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataSetEarlier.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataSetListResponse.FromString,
                _registered_method=True)
        self.ListDataSetByLater = channel.unary_unary(
                '/data.DataService/ListDataSetByLater',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataSetLater.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataSetListResponse.FromString,
                _registered_method=True)
        self.ListDataSetByRange = channel.unary_unary(
                '/data.DataService/ListDataSetByRange',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataSetRange.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataSetListResponse.FromString,
                _registered_method=True)
        self.CreateData = channel.unary_unary(
                '/data.DataService/CreateData',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataSchema.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataChangeResponse.FromString,
                _registered_method=True)
        self.CreateDataMultiple = channel.unary_unary(
                '/data.DataService/CreateDataMultiple',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataMultipleSchema.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataChangeResponse.FromString,
                _registered_method=True)
        self.DeleteData = channel.unary_unary(
                '/data.DataService/DeleteData',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataTime.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataChangeResponse.FromString,
                _registered_method=True)
        self.ReadDataTimestamp = channel.unary_unary(
                '/data.DataService/ReadDataTimestamp',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataTime.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.TimestampReadResponse.FromString,
                _registered_method=True)
        self.ListDataTimestampByEarlier = channel.unary_unary(
                '/data.DataService/ListDataTimestampByEarlier',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataEarlier.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.TimestampListResponse.FromString,
                _registered_method=True)
        self.ListDataTimestampByLater = channel.unary_unary(
                '/data.DataService/ListDataTimestampByLater',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataLater.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.TimestampListResponse.FromString,
                _registered_method=True)
        self.ListDataTimestampByRange = channel.unary_unary(
                '/data.DataService/ListDataTimestampByRange',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataRange.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.TimestampListResponse.FromString,
                _registered_method=True)
        self.ReadDataGroupTimestamp = channel.unary_unary(
                '/data.DataService/ReadDataGroupTimestamp',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataGroupTime.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.TimestampReadResponse.FromString,
                _registered_method=True)
        self.ListDataGroupTimestampByEarlier = channel.unary_unary(
                '/data.DataService/ListDataGroupTimestampByEarlier',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataGroupEarlier.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.TimestampListResponse.FromString,
                _registered_method=True)
        self.ListDataGroupTimestampByLater = channel.unary_unary(
                '/data.DataService/ListDataGroupTimestampByLater',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataGroupLater.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.TimestampListResponse.FromString,
                _registered_method=True)
        self.ListDataGroupTimestampByRange = channel.unary_unary(
                '/data.DataService/ListDataGroupTimestampByRange',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataGroupRange.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.TimestampListResponse.FromString,
                _registered_method=True)
        self.CountData = channel.unary_unary(
                '/data.DataService/CountData',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataTime.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataCountResponse.FromString,
                _registered_method=True)
        self.CountDataByEarlier = channel.unary_unary(
                '/data.DataService/CountDataByEarlier',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataEarlier.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataCountResponse.FromString,
                _registered_method=True)
        self.CountDataByLater = channel.unary_unary(
                '/data.DataService/CountDataByLater',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataLater.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataCountResponse.FromString,
                _registered_method=True)
        self.CountDataByRange = channel.unary_unary(
                '/data.DataService/CountDataByRange',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataRange.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataCountResponse.FromString,
                _registered_method=True)
        self.CountDataGroup = channel.unary_unary(
                '/data.DataService/CountDataGroup',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataGroupTime.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataCountResponse.FromString,
                _registered_method=True)
        self.CountDataGroupByEarlier = channel.unary_unary(
                '/data.DataService/CountDataGroupByEarlier',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataGroupEarlier.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataCountResponse.FromString,
                _registered_method=True)
        self.CountDataGroupByLater = channel.unary_unary(
                '/data.DataService/CountDataGroupByLater',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataGroupLater.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataCountResponse.FromString,
                _registered_method=True)
        self.CountDataGroupByRange = channel.unary_unary(
                '/data.DataService/CountDataGroupByRange',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataGroupRange.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataCountResponse.FromString,
                _registered_method=True)


class DataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReadData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDataByTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDataByEarlier(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDataByLater(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDataByRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDataByNumberBefore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDataByNumberAfter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDataGroupByTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDataGroupByEarlier(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDataGroupByLater(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDataGroupByRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDataGroupByNumberBefore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDataGroupByNumberAfter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadDataSet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDataSetByTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDataSetByEarlier(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDataSetByLater(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDataSetByRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateDataMultiple(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadDataTimestamp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDataTimestampByEarlier(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDataTimestampByLater(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDataTimestampByRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadDataGroupTimestamp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDataGroupTimestampByEarlier(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDataGroupTimestampByLater(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDataGroupTimestampByRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CountData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CountDataByEarlier(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CountDataByLater(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CountDataByRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CountDataGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CountDataGroupByEarlier(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CountDataGroupByLater(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CountDataGroupByRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReadData': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadData,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataTime.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataReadResponse.SerializeToString,
            ),
            'ListDataByTime': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDataByTime,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataTime.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataListResponse.SerializeToString,
            ),
            'ListDataByEarlier': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDataByEarlier,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataEarlier.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataListResponse.SerializeToString,
            ),
            'ListDataByLater': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDataByLater,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataLater.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataListResponse.SerializeToString,
            ),
            'ListDataByRange': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDataByRange,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataRange.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataListResponse.SerializeToString,
            ),
            'ListDataByNumberBefore': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDataByNumberBefore,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataNumber.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataListResponse.SerializeToString,
            ),
            'ListDataByNumberAfter': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDataByNumberAfter,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataNumber.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataListResponse.SerializeToString,
            ),
            'ListDataGroupByTime': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDataGroupByTime,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataGroupTime.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataListResponse.SerializeToString,
            ),
            'ListDataGroupByEarlier': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDataGroupByEarlier,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataGroupEarlier.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataListResponse.SerializeToString,
            ),
            'ListDataGroupByLater': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDataGroupByLater,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataGroupLater.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataListResponse.SerializeToString,
            ),
            'ListDataGroupByRange': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDataGroupByRange,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataGroupRange.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataListResponse.SerializeToString,
            ),
            'ListDataGroupByNumberBefore': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDataGroupByNumberBefore,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataGroupNumber.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataListResponse.SerializeToString,
            ),
            'ListDataGroupByNumberAfter': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDataGroupByNumberAfter,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataGroupNumber.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataListResponse.SerializeToString,
            ),
            'ReadDataSet': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadDataSet,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataSetTime.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataSetReadResponse.SerializeToString,
            ),
            'ListDataSetByTime': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDataSetByTime,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataSetTime.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataSetListResponse.SerializeToString,
            ),
            'ListDataSetByEarlier': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDataSetByEarlier,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataSetEarlier.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataSetListResponse.SerializeToString,
            ),
            'ListDataSetByLater': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDataSetByLater,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataSetLater.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataSetListResponse.SerializeToString,
            ),
            'ListDataSetByRange': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDataSetByRange,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataSetRange.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataSetListResponse.SerializeToString,
            ),
            'CreateData': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateData,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataSchema.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataChangeResponse.SerializeToString,
            ),
            'CreateDataMultiple': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDataMultiple,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataMultipleSchema.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataChangeResponse.SerializeToString,
            ),
            'DeleteData': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteData,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataTime.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataChangeResponse.SerializeToString,
            ),
            'ReadDataTimestamp': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadDataTimestamp,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataTime.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.TimestampReadResponse.SerializeToString,
            ),
            'ListDataTimestampByEarlier': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDataTimestampByEarlier,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataEarlier.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.TimestampListResponse.SerializeToString,
            ),
            'ListDataTimestampByLater': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDataTimestampByLater,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataLater.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.TimestampListResponse.SerializeToString,
            ),
            'ListDataTimestampByRange': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDataTimestampByRange,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataRange.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.TimestampListResponse.SerializeToString,
            ),
            'ReadDataGroupTimestamp': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadDataGroupTimestamp,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataGroupTime.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.TimestampReadResponse.SerializeToString,
            ),
            'ListDataGroupTimestampByEarlier': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDataGroupTimestampByEarlier,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataGroupEarlier.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.TimestampListResponse.SerializeToString,
            ),
            'ListDataGroupTimestampByLater': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDataGroupTimestampByLater,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataGroupLater.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.TimestampListResponse.SerializeToString,
            ),
            'ListDataGroupTimestampByRange': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDataGroupTimestampByRange,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataGroupRange.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.TimestampListResponse.SerializeToString,
            ),
            'CountData': grpc.unary_unary_rpc_method_handler(
                    servicer.CountData,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataTime.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataCountResponse.SerializeToString,
            ),
            'CountDataByEarlier': grpc.unary_unary_rpc_method_handler(
                    servicer.CountDataByEarlier,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataEarlier.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataCountResponse.SerializeToString,
            ),
            'CountDataByLater': grpc.unary_unary_rpc_method_handler(
                    servicer.CountDataByLater,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataLater.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataCountResponse.SerializeToString,
            ),
            'CountDataByRange': grpc.unary_unary_rpc_method_handler(
                    servicer.CountDataByRange,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataRange.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataCountResponse.SerializeToString,
            ),
            'CountDataGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.CountDataGroup,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataGroupTime.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataCountResponse.SerializeToString,
            ),
            'CountDataGroupByEarlier': grpc.unary_unary_rpc_method_handler(
                    servicer.CountDataGroupByEarlier,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataGroupEarlier.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataCountResponse.SerializeToString,
            ),
            'CountDataGroupByLater': grpc.unary_unary_rpc_method_handler(
                    servicer.CountDataGroupByLater,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataGroupLater.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataCountResponse.SerializeToString,
            ),
            'CountDataGroupByRange': grpc.unary_unary_rpc_method_handler(
                    servicer.CountDataGroupByRange,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataGroupRange.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataCountResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'data.DataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('data.DataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReadData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/ReadData',
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataTime.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDataByTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/ListDataByTime',
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataTime.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDataByEarlier(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/ListDataByEarlier',
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataEarlier.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDataByLater(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/ListDataByLater',
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataLater.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDataByRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/ListDataByRange',
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataRange.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDataByNumberBefore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/ListDataByNumberBefore',
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataNumber.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDataByNumberAfter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/ListDataByNumberAfter',
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataNumber.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDataGroupByTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/ListDataGroupByTime',
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataGroupTime.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDataGroupByEarlier(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/ListDataGroupByEarlier',
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataGroupEarlier.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDataGroupByLater(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/ListDataGroupByLater',
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataGroupLater.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDataGroupByRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/ListDataGroupByRange',
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataGroupRange.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDataGroupByNumberBefore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/ListDataGroupByNumberBefore',
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataGroupNumber.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDataGroupByNumberAfter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/ListDataGroupByNumberAfter',
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataGroupNumber.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadDataSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/ReadDataSet',
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataSetTime.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataSetReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDataSetByTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/ListDataSetByTime',
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataSetTime.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataSetListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDataSetByEarlier(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/ListDataSetByEarlier',
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataSetEarlier.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataSetListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDataSetByLater(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/ListDataSetByLater',
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataSetLater.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataSetListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDataSetByRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/ListDataSetByRange',
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataSetRange.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataSetListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/CreateData',
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataSchema.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateDataMultiple(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/CreateDataMultiple',
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataMultipleSchema.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/DeleteData',
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataTime.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadDataTimestamp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/ReadDataTimestamp',
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataTime.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.TimestampReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDataTimestampByEarlier(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/ListDataTimestampByEarlier',
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataEarlier.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.TimestampListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDataTimestampByLater(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/ListDataTimestampByLater',
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataLater.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.TimestampListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDataTimestampByRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/ListDataTimestampByRange',
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataRange.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.TimestampListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadDataGroupTimestamp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/ReadDataGroupTimestamp',
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataGroupTime.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.TimestampReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDataGroupTimestampByEarlier(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/ListDataGroupTimestampByEarlier',
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataGroupEarlier.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.TimestampListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDataGroupTimestampByLater(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/ListDataGroupTimestampByLater',
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataGroupLater.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.TimestampListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDataGroupTimestampByRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/ListDataGroupTimestampByRange',
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataGroupRange.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.TimestampListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CountData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/CountData',
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataTime.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataCountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CountDataByEarlier(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/CountDataByEarlier',
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataEarlier.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataCountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CountDataByLater(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/CountDataByLater',
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataLater.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataCountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CountDataByRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/CountDataByRange',
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataRange.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataCountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CountDataGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/CountDataGroup',
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataGroupTime.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataCountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CountDataGroupByEarlier(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/CountDataGroupByEarlier',
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataGroupEarlier.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataCountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CountDataGroupByLater(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/CountDataGroupByLater',
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataGroupLater.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataCountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CountDataGroupByRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/CountDataGroupByRange',
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataGroupRange.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_data__pb2.DataCountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
