# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from bbthings_grpc.proto.resource import set_pb2 as bbthings__grpc_dot_proto_dot_resource_dot_set__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in bbthings_grpc/proto/resource/set_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SetServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReadSet = channel.unary_unary(
                '/set.SetService/ReadSet',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetId.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetReadResponse.FromString,
                _registered_method=True)
        self.ListSetByIds = channel.unary_unary(
                '/set.SetService/ListSetByIds',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetIds.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetListResponse.FromString,
                _registered_method=True)
        self.ListSetByTemplate = channel.unary_unary(
                '/set.SetService/ListSetByTemplate',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetTemplateId.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetListResponse.FromString,
                _registered_method=True)
        self.ListSetByName = channel.unary_unary(
                '/set.SetService/ListSetByName',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetName.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetListResponse.FromString,
                _registered_method=True)
        self.ListSetOption = channel.unary_unary(
                '/set.SetService/ListSetOption',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetOption.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetListResponse.FromString,
                _registered_method=True)
        self.CreateSet = channel.unary_unary(
                '/set.SetService/CreateSet',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetSchema.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetCreateResponse.FromString,
                _registered_method=True)
        self.UpdateSet = channel.unary_unary(
                '/set.SetService/UpdateSet',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetUpdate.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetChangeResponse.FromString,
                _registered_method=True)
        self.DeleteSet = channel.unary_unary(
                '/set.SetService/DeleteSet',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetId.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetChangeResponse.FromString,
                _registered_method=True)
        self.AddSetMember = channel.unary_unary(
                '/set.SetService/AddSetMember',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetMemberRequest.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetChangeResponse.FromString,
                _registered_method=True)
        self.RemoveSetMember = channel.unary_unary(
                '/set.SetService/RemoveSetMember',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetMemberRequest.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetChangeResponse.FromString,
                _registered_method=True)
        self.SwapSetMember = channel.unary_unary(
                '/set.SetService/SwapSetMember',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetMemberSwap.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetChangeResponse.FromString,
                _registered_method=True)
        self.ReadSetTemplate = channel.unary_unary(
                '/set.SetService/ReadSetTemplate',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetTemplateId.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.TemplateReadResponse.FromString,
                _registered_method=True)
        self.ListSetTemplateByIds = channel.unary_unary(
                '/set.SetService/ListSetTemplateByIds',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetTemplateIds.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.TemplateListResponse.FromString,
                _registered_method=True)
        self.ListSetTemplateByName = channel.unary_unary(
                '/set.SetService/ListSetTemplateByName',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetTemplateName.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.TemplateListResponse.FromString,
                _registered_method=True)
        self.ListSetTemplateOption = channel.unary_unary(
                '/set.SetService/ListSetTemplateOption',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetTemplateOption.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.TemplateListResponse.FromString,
                _registered_method=True)
        self.CreateSetTemplate = channel.unary_unary(
                '/set.SetService/CreateSetTemplate',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetTemplateSchema.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.TemplateCreateResponse.FromString,
                _registered_method=True)
        self.UpdateSetTemplate = channel.unary_unary(
                '/set.SetService/UpdateSetTemplate',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetTemplateUpdate.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.TemplateChangeResponse.FromString,
                _registered_method=True)
        self.DeleteSetTemplate = channel.unary_unary(
                '/set.SetService/DeleteSetTemplate',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetTemplateId.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.TemplateChangeResponse.FromString,
                _registered_method=True)
        self.AddSetTemplateMember = channel.unary_unary(
                '/set.SetService/AddSetTemplateMember',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetTemplateMemberRequest.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.TemplateChangeResponse.FromString,
                _registered_method=True)
        self.RemoveSetTemplateMember = channel.unary_unary(
                '/set.SetService/RemoveSetTemplateMember',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetTemplateMemberRequest.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.TemplateChangeResponse.FromString,
                _registered_method=True)
        self.SwapSetTemplateMember = channel.unary_unary(
                '/set.SetService/SwapSetTemplateMember',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetTemplateMemberSwap.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.TemplateChangeResponse.FromString,
                _registered_method=True)


class SetServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReadSet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSetByIds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSetByTemplate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSetByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSetOption(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddSetMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveSetMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SwapSetMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadSetTemplate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSetTemplateByIds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSetTemplateByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSetTemplateOption(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSetTemplate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSetTemplate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSetTemplate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddSetTemplateMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveSetTemplateMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SwapSetTemplateMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SetServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReadSet': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadSet,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetId.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetReadResponse.SerializeToString,
            ),
            'ListSetByIds': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSetByIds,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetIds.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetListResponse.SerializeToString,
            ),
            'ListSetByTemplate': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSetByTemplate,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetTemplateId.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetListResponse.SerializeToString,
            ),
            'ListSetByName': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSetByName,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetName.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetListResponse.SerializeToString,
            ),
            'ListSetOption': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSetOption,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetOption.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetListResponse.SerializeToString,
            ),
            'CreateSet': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSet,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetSchema.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetCreateResponse.SerializeToString,
            ),
            'UpdateSet': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSet,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetUpdate.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetChangeResponse.SerializeToString,
            ),
            'DeleteSet': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSet,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetId.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetChangeResponse.SerializeToString,
            ),
            'AddSetMember': grpc.unary_unary_rpc_method_handler(
                    servicer.AddSetMember,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetMemberRequest.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetChangeResponse.SerializeToString,
            ),
            'RemoveSetMember': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveSetMember,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetMemberRequest.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetChangeResponse.SerializeToString,
            ),
            'SwapSetMember': grpc.unary_unary_rpc_method_handler(
                    servicer.SwapSetMember,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetMemberSwap.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetChangeResponse.SerializeToString,
            ),
            'ReadSetTemplate': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadSetTemplate,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetTemplateId.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.TemplateReadResponse.SerializeToString,
            ),
            'ListSetTemplateByIds': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSetTemplateByIds,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetTemplateIds.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.TemplateListResponse.SerializeToString,
            ),
            'ListSetTemplateByName': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSetTemplateByName,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetTemplateName.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.TemplateListResponse.SerializeToString,
            ),
            'ListSetTemplateOption': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSetTemplateOption,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetTemplateOption.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.TemplateListResponse.SerializeToString,
            ),
            'CreateSetTemplate': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSetTemplate,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetTemplateSchema.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.TemplateCreateResponse.SerializeToString,
            ),
            'UpdateSetTemplate': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSetTemplate,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetTemplateUpdate.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.TemplateChangeResponse.SerializeToString,
            ),
            'DeleteSetTemplate': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSetTemplate,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetTemplateId.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.TemplateChangeResponse.SerializeToString,
            ),
            'AddSetTemplateMember': grpc.unary_unary_rpc_method_handler(
                    servicer.AddSetTemplateMember,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetTemplateMemberRequest.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.TemplateChangeResponse.SerializeToString,
            ),
            'RemoveSetTemplateMember': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveSetTemplateMember,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetTemplateMemberRequest.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.TemplateChangeResponse.SerializeToString,
            ),
            'SwapSetTemplateMember': grpc.unary_unary_rpc_method_handler(
                    servicer.SwapSetTemplateMember,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetTemplateMemberSwap.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.TemplateChangeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'set.SetService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('set.SetService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SetService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReadSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/set.SetService/ReadSet',
            bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetId.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSetByIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/set.SetService/ListSetByIds',
            bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetIds.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSetByTemplate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/set.SetService/ListSetByTemplate',
            bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetTemplateId.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSetByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/set.SetService/ListSetByName',
            bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetName.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSetOption(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/set.SetService/ListSetOption',
            bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetOption.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/set.SetService/CreateSet',
            bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetSchema.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetCreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/set.SetService/UpdateSet',
            bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetUpdate.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/set.SetService/DeleteSet',
            bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetId.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddSetMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/set.SetService/AddSetMember',
            bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetMemberRequest.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveSetMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/set.SetService/RemoveSetMember',
            bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetMemberRequest.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SwapSetMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/set.SetService/SwapSetMember',
            bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetMemberSwap.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadSetTemplate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/set.SetService/ReadSetTemplate',
            bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetTemplateId.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.TemplateReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSetTemplateByIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/set.SetService/ListSetTemplateByIds',
            bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetTemplateIds.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.TemplateListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSetTemplateByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/set.SetService/ListSetTemplateByName',
            bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetTemplateName.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.TemplateListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSetTemplateOption(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/set.SetService/ListSetTemplateOption',
            bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetTemplateOption.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.TemplateListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSetTemplate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/set.SetService/CreateSetTemplate',
            bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetTemplateSchema.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.TemplateCreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSetTemplate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/set.SetService/UpdateSetTemplate',
            bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetTemplateUpdate.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.TemplateChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSetTemplate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/set.SetService/DeleteSetTemplate',
            bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetTemplateId.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.TemplateChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddSetTemplateMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/set.SetService/AddSetTemplateMember',
            bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetTemplateMemberRequest.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.TemplateChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveSetTemplateMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/set.SetService/RemoveSetTemplateMember',
            bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetTemplateMemberRequest.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.TemplateChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SwapSetTemplateMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/set.SetService/SwapSetTemplateMember',
            bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.SetTemplateMemberSwap.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_set__pb2.TemplateChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
