# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from bbthings_grpc.proto.resource import slice_pb2 as bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in bbthings_grpc/proto/resource/slice_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SliceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReadSlice = channel.unary_unary(
                '/slice.SliceService/ReadSlice',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceId.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceReadResponse.FromString,
                _registered_method=True)
        self.ListSliceByIds = channel.unary_unary(
                '/slice.SliceService/ListSliceByIds',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceIds.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceListResponse.FromString,
                _registered_method=True)
        self.ListSliceByTime = channel.unary_unary(
                '/slice.SliceService/ListSliceByTime',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceTime.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceListResponse.FromString,
                _registered_method=True)
        self.ListSliceByRange = channel.unary_unary(
                '/slice.SliceService/ListSliceByRange',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceRange.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceListResponse.FromString,
                _registered_method=True)
        self.ListSliceByNameTime = channel.unary_unary(
                '/slice.SliceService/ListSliceByNameTime',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceNameTime.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceListResponse.FromString,
                _registered_method=True)
        self.ListSliceByNameRange = channel.unary_unary(
                '/slice.SliceService/ListSliceByNameRange',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceNameRange.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceListResponse.FromString,
                _registered_method=True)
        self.ListSliceOption = channel.unary_unary(
                '/slice.SliceService/ListSliceOption',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceOption.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceListResponse.FromString,
                _registered_method=True)
        self.ListSliceGroupByTime = channel.unary_unary(
                '/slice.SliceService/ListSliceGroupByTime',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceGroupTime.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceListResponse.FromString,
                _registered_method=True)
        self.ListSliceGroupByRange = channel.unary_unary(
                '/slice.SliceService/ListSliceGroupByRange',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceGroupRange.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceListResponse.FromString,
                _registered_method=True)
        self.ListSliceGroupOption = channel.unary_unary(
                '/slice.SliceService/ListSliceGroupOption',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceGroupOption.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceListResponse.FromString,
                _registered_method=True)
        self.CreateSlice = channel.unary_unary(
                '/slice.SliceService/CreateSlice',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceSchema.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceCreateResponse.FromString,
                _registered_method=True)
        self.UpdateSlice = channel.unary_unary(
                '/slice.SliceService/UpdateSlice',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceUpdate.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceChangeResponse.FromString,
                _registered_method=True)
        self.DeleteSlice = channel.unary_unary(
                '/slice.SliceService/DeleteSlice',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceId.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceChangeResponse.FromString,
                _registered_method=True)
        self.ReadSliceSet = channel.unary_unary(
                '/slice.SliceService/ReadSliceSet',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceId.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceSetReadResponse.FromString,
                _registered_method=True)
        self.ListSliceSetByIds = channel.unary_unary(
                '/slice.SliceService/ListSliceSetByIds',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceIds.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceSetListResponse.FromString,
                _registered_method=True)
        self.ListSliceSetByTime = channel.unary_unary(
                '/slice.SliceService/ListSliceSetByTime',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceSetTime.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceSetListResponse.FromString,
                _registered_method=True)
        self.ListSliceSetByRange = channel.unary_unary(
                '/slice.SliceService/ListSliceSetByRange',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceSetRange.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceSetListResponse.FromString,
                _registered_method=True)
        self.ListSliceSetByNameTime = channel.unary_unary(
                '/slice.SliceService/ListSliceSetByNameTime',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceNameTime.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceSetListResponse.FromString,
                _registered_method=True)
        self.ListSliceSetByNameRange = channel.unary_unary(
                '/slice.SliceService/ListSliceSetByNameRange',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceNameRange.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceSetListResponse.FromString,
                _registered_method=True)
        self.ListSliceSetOption = channel.unary_unary(
                '/slice.SliceService/ListSliceSetOption',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceSetOption.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceSetListResponse.FromString,
                _registered_method=True)
        self.CreateSliceSet = channel.unary_unary(
                '/slice.SliceService/CreateSliceSet',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceSetSchema.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceCreateResponse.FromString,
                _registered_method=True)
        self.UpdateSliceSet = channel.unary_unary(
                '/slice.SliceService/UpdateSliceSet',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceUpdate.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceChangeResponse.FromString,
                _registered_method=True)
        self.DeleteSliceSet = channel.unary_unary(
                '/slice.SliceService/DeleteSliceSet',
                request_serializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceId.SerializeToString,
                response_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceChangeResponse.FromString,
                _registered_method=True)


class SliceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReadSlice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSliceByIds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSliceByTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSliceByRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSliceByNameTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSliceByNameRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSliceOption(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSliceGroupByTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSliceGroupByRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSliceGroupOption(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSlice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSlice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSlice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadSliceSet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSliceSetByIds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSliceSetByTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSliceSetByRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSliceSetByNameTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSliceSetByNameRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSliceSetOption(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSliceSet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSliceSet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSliceSet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SliceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReadSlice': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadSlice,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceId.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceReadResponse.SerializeToString,
            ),
            'ListSliceByIds': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSliceByIds,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceIds.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceListResponse.SerializeToString,
            ),
            'ListSliceByTime': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSliceByTime,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceTime.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceListResponse.SerializeToString,
            ),
            'ListSliceByRange': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSliceByRange,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceRange.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceListResponse.SerializeToString,
            ),
            'ListSliceByNameTime': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSliceByNameTime,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceNameTime.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceListResponse.SerializeToString,
            ),
            'ListSliceByNameRange': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSliceByNameRange,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceNameRange.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceListResponse.SerializeToString,
            ),
            'ListSliceOption': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSliceOption,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceOption.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceListResponse.SerializeToString,
            ),
            'ListSliceGroupByTime': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSliceGroupByTime,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceGroupTime.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceListResponse.SerializeToString,
            ),
            'ListSliceGroupByRange': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSliceGroupByRange,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceGroupRange.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceListResponse.SerializeToString,
            ),
            'ListSliceGroupOption': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSliceGroupOption,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceGroupOption.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceListResponse.SerializeToString,
            ),
            'CreateSlice': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSlice,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceSchema.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceCreateResponse.SerializeToString,
            ),
            'UpdateSlice': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSlice,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceUpdate.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceChangeResponse.SerializeToString,
            ),
            'DeleteSlice': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSlice,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceId.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceChangeResponse.SerializeToString,
            ),
            'ReadSliceSet': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadSliceSet,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceId.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceSetReadResponse.SerializeToString,
            ),
            'ListSliceSetByIds': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSliceSetByIds,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceIds.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceSetListResponse.SerializeToString,
            ),
            'ListSliceSetByTime': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSliceSetByTime,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceSetTime.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceSetListResponse.SerializeToString,
            ),
            'ListSliceSetByRange': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSliceSetByRange,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceSetRange.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceSetListResponse.SerializeToString,
            ),
            'ListSliceSetByNameTime': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSliceSetByNameTime,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceNameTime.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceSetListResponse.SerializeToString,
            ),
            'ListSliceSetByNameRange': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSliceSetByNameRange,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceNameRange.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceSetListResponse.SerializeToString,
            ),
            'ListSliceSetOption': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSliceSetOption,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceSetOption.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceSetListResponse.SerializeToString,
            ),
            'CreateSliceSet': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSliceSet,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceSetSchema.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceCreateResponse.SerializeToString,
            ),
            'UpdateSliceSet': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSliceSet,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceUpdate.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceChangeResponse.SerializeToString,
            ),
            'DeleteSliceSet': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSliceSet,
                    request_deserializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceId.FromString,
                    response_serializer=bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceChangeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'slice.SliceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('slice.SliceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SliceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReadSlice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slice.SliceService/ReadSlice',
            bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceId.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSliceByIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slice.SliceService/ListSliceByIds',
            bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceIds.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSliceByTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slice.SliceService/ListSliceByTime',
            bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceTime.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSliceByRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slice.SliceService/ListSliceByRange',
            bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceRange.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSliceByNameTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slice.SliceService/ListSliceByNameTime',
            bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceNameTime.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSliceByNameRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slice.SliceService/ListSliceByNameRange',
            bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceNameRange.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSliceOption(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slice.SliceService/ListSliceOption',
            bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceOption.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSliceGroupByTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slice.SliceService/ListSliceGroupByTime',
            bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceGroupTime.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSliceGroupByRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slice.SliceService/ListSliceGroupByRange',
            bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceGroupRange.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSliceGroupOption(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slice.SliceService/ListSliceGroupOption',
            bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceGroupOption.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSlice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slice.SliceService/CreateSlice',
            bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceSchema.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceCreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSlice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slice.SliceService/UpdateSlice',
            bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceUpdate.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSlice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slice.SliceService/DeleteSlice',
            bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceId.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadSliceSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slice.SliceService/ReadSliceSet',
            bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceId.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceSetReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSliceSetByIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slice.SliceService/ListSliceSetByIds',
            bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceIds.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceSetListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSliceSetByTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slice.SliceService/ListSliceSetByTime',
            bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceSetTime.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceSetListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSliceSetByRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slice.SliceService/ListSliceSetByRange',
            bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceSetRange.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceSetListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSliceSetByNameTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slice.SliceService/ListSliceSetByNameTime',
            bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceNameTime.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceSetListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSliceSetByNameRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slice.SliceService/ListSliceSetByNameRange',
            bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceNameRange.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceSetListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSliceSetOption(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slice.SliceService/ListSliceSetOption',
            bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceSetOption.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceSetListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSliceSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slice.SliceService/CreateSliceSet',
            bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceSetSchema.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceCreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSliceSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slice.SliceService/UpdateSliceSet',
            bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceUpdate.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSliceSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slice.SliceService/DeleteSliceSet',
            bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceId.SerializeToString,
            bbthings__grpc_dot_proto_dot_resource_dot_slice__pb2.SliceChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
