# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from resource import buffer_pb2 as resource_dot_buffer__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in resource/buffer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BufferServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReadBuffer = channel.unary_unary(
                '/buffer.BufferService/ReadBuffer',
                request_serializer=resource_dot_buffer__pb2.BufferId.SerializeToString,
                response_deserializer=resource_dot_buffer__pb2.BufferReadResponse.FromString,
                _registered_method=True)
        self.ReadBufferByTime = channel.unary_unary(
                '/buffer.BufferService/ReadBufferByTime',
                request_serializer=resource_dot_buffer__pb2.BufferTime.SerializeToString,
                response_deserializer=resource_dot_buffer__pb2.BufferReadResponse.FromString,
                _registered_method=True)
        self.ListBufferByIds = channel.unary_unary(
                '/buffer.BufferService/ListBufferByIds',
                request_serializer=resource_dot_buffer__pb2.BufferIds.SerializeToString,
                response_deserializer=resource_dot_buffer__pb2.BufferListResponse.FromString,
                _registered_method=True)
        self.ListBufferByTime = channel.unary_unary(
                '/buffer.BufferService/ListBufferByTime',
                request_serializer=resource_dot_buffer__pb2.BufferTime.SerializeToString,
                response_deserializer=resource_dot_buffer__pb2.BufferListResponse.FromString,
                _registered_method=True)
        self.ListBufferByLatest = channel.unary_unary(
                '/buffer.BufferService/ListBufferByLatest',
                request_serializer=resource_dot_buffer__pb2.BufferLatest.SerializeToString,
                response_deserializer=resource_dot_buffer__pb2.BufferListResponse.FromString,
                _registered_method=True)
        self.ListBufferByRange = channel.unary_unary(
                '/buffer.BufferService/ListBufferByRange',
                request_serializer=resource_dot_buffer__pb2.BufferRange.SerializeToString,
                response_deserializer=resource_dot_buffer__pb2.BufferListResponse.FromString,
                _registered_method=True)
        self.ListBufferByNumberBefore = channel.unary_unary(
                '/buffer.BufferService/ListBufferByNumberBefore',
                request_serializer=resource_dot_buffer__pb2.BufferNumber.SerializeToString,
                response_deserializer=resource_dot_buffer__pb2.BufferListResponse.FromString,
                _registered_method=True)
        self.ListBufferByNumberAfter = channel.unary_unary(
                '/buffer.BufferService/ListBufferByNumberAfter',
                request_serializer=resource_dot_buffer__pb2.BufferNumber.SerializeToString,
                response_deserializer=resource_dot_buffer__pb2.BufferListResponse.FromString,
                _registered_method=True)
        self.ReadBufferFirst = channel.unary_unary(
                '/buffer.BufferService/ReadBufferFirst',
                request_serializer=resource_dot_buffer__pb2.BufferSelector.SerializeToString,
                response_deserializer=resource_dot_buffer__pb2.BufferReadResponse.FromString,
                _registered_method=True)
        self.ReadBufferLast = channel.unary_unary(
                '/buffer.BufferService/ReadBufferLast',
                request_serializer=resource_dot_buffer__pb2.BufferSelector.SerializeToString,
                response_deserializer=resource_dot_buffer__pb2.BufferReadResponse.FromString,
                _registered_method=True)
        self.ListBufferFirst = channel.unary_unary(
                '/buffer.BufferService/ListBufferFirst',
                request_serializer=resource_dot_buffer__pb2.BuffersSelector.SerializeToString,
                response_deserializer=resource_dot_buffer__pb2.BufferListResponse.FromString,
                _registered_method=True)
        self.ListBufferFirstOffset = channel.unary_unary(
                '/buffer.BufferService/ListBufferFirstOffset',
                request_serializer=resource_dot_buffer__pb2.BuffersSelector.SerializeToString,
                response_deserializer=resource_dot_buffer__pb2.BufferListResponse.FromString,
                _registered_method=True)
        self.ListBufferLast = channel.unary_unary(
                '/buffer.BufferService/ListBufferLast',
                request_serializer=resource_dot_buffer__pb2.BuffersSelector.SerializeToString,
                response_deserializer=resource_dot_buffer__pb2.BufferListResponse.FromString,
                _registered_method=True)
        self.ListBufferLastOffset = channel.unary_unary(
                '/buffer.BufferService/ListBufferLastOffset',
                request_serializer=resource_dot_buffer__pb2.BuffersSelector.SerializeToString,
                response_deserializer=resource_dot_buffer__pb2.BufferListResponse.FromString,
                _registered_method=True)
        self.ListBufferGroupByTime = channel.unary_unary(
                '/buffer.BufferService/ListBufferGroupByTime',
                request_serializer=resource_dot_buffer__pb2.BufferGroupTime.SerializeToString,
                response_deserializer=resource_dot_buffer__pb2.BufferListResponse.FromString,
                _registered_method=True)
        self.ListBufferGroupByLatest = channel.unary_unary(
                '/buffer.BufferService/ListBufferGroupByLatest',
                request_serializer=resource_dot_buffer__pb2.BufferGroupLatest.SerializeToString,
                response_deserializer=resource_dot_buffer__pb2.BufferListResponse.FromString,
                _registered_method=True)
        self.ListBufferGroupByRange = channel.unary_unary(
                '/buffer.BufferService/ListBufferGroupByRange',
                request_serializer=resource_dot_buffer__pb2.BufferGroupRange.SerializeToString,
                response_deserializer=resource_dot_buffer__pb2.BufferListResponse.FromString,
                _registered_method=True)
        self.ListBufferGroupByNumberBefore = channel.unary_unary(
                '/buffer.BufferService/ListBufferGroupByNumberBefore',
                request_serializer=resource_dot_buffer__pb2.BufferGroupNumber.SerializeToString,
                response_deserializer=resource_dot_buffer__pb2.BufferListResponse.FromString,
                _registered_method=True)
        self.ListBufferGroupByNumberAfter = channel.unary_unary(
                '/buffer.BufferService/ListBufferGroupByNumberAfter',
                request_serializer=resource_dot_buffer__pb2.BufferGroupNumber.SerializeToString,
                response_deserializer=resource_dot_buffer__pb2.BufferListResponse.FromString,
                _registered_method=True)
        self.ReadBufferGroupFirst = channel.unary_unary(
                '/buffer.BufferService/ReadBufferGroupFirst',
                request_serializer=resource_dot_buffer__pb2.BufferGroupSelector.SerializeToString,
                response_deserializer=resource_dot_buffer__pb2.BufferReadResponse.FromString,
                _registered_method=True)
        self.ReadBufferGroupLast = channel.unary_unary(
                '/buffer.BufferService/ReadBufferGroupLast',
                request_serializer=resource_dot_buffer__pb2.BufferGroupSelector.SerializeToString,
                response_deserializer=resource_dot_buffer__pb2.BufferReadResponse.FromString,
                _registered_method=True)
        self.ListBufferGroupFirst = channel.unary_unary(
                '/buffer.BufferService/ListBufferGroupFirst',
                request_serializer=resource_dot_buffer__pb2.BuffersGroupSelector.SerializeToString,
                response_deserializer=resource_dot_buffer__pb2.BufferListResponse.FromString,
                _registered_method=True)
        self.ListBufferGroupFirstOffset = channel.unary_unary(
                '/buffer.BufferService/ListBufferGroupFirstOffset',
                request_serializer=resource_dot_buffer__pb2.BuffersGroupSelector.SerializeToString,
                response_deserializer=resource_dot_buffer__pb2.BufferListResponse.FromString,
                _registered_method=True)
        self.ListBufferGroupLast = channel.unary_unary(
                '/buffer.BufferService/ListBufferGroupLast',
                request_serializer=resource_dot_buffer__pb2.BuffersGroupSelector.SerializeToString,
                response_deserializer=resource_dot_buffer__pb2.BufferListResponse.FromString,
                _registered_method=True)
        self.ListBufferGroupLastOffset = channel.unary_unary(
                '/buffer.BufferService/ListBufferGroupLastOffset',
                request_serializer=resource_dot_buffer__pb2.BuffersGroupSelector.SerializeToString,
                response_deserializer=resource_dot_buffer__pb2.BufferListResponse.FromString,
                _registered_method=True)
        self.ReadBufferSet = channel.unary_unary(
                '/buffer.BufferService/ReadBufferSet',
                request_serializer=resource_dot_buffer__pb2.BufferSetTime.SerializeToString,
                response_deserializer=resource_dot_buffer__pb2.BufferSetReadResponse.FromString,
                _registered_method=True)
        self.ListBufferSetByTime = channel.unary_unary(
                '/buffer.BufferService/ListBufferSetByTime',
                request_serializer=resource_dot_buffer__pb2.BufferSetTime.SerializeToString,
                response_deserializer=resource_dot_buffer__pb2.BufferSetListResponse.FromString,
                _registered_method=True)
        self.ListBufferSetByLatest = channel.unary_unary(
                '/buffer.BufferService/ListBufferSetByLatest',
                request_serializer=resource_dot_buffer__pb2.BufferSetLatest.SerializeToString,
                response_deserializer=resource_dot_buffer__pb2.BufferSetListResponse.FromString,
                _registered_method=True)
        self.ListBufferSetByRange = channel.unary_unary(
                '/buffer.BufferService/ListBufferSetByRange',
                request_serializer=resource_dot_buffer__pb2.BufferSetRange.SerializeToString,
                response_deserializer=resource_dot_buffer__pb2.BufferSetListResponse.FromString,
                _registered_method=True)
        self.CreateBuffer = channel.unary_unary(
                '/buffer.BufferService/CreateBuffer',
                request_serializer=resource_dot_buffer__pb2.BufferSchema.SerializeToString,
                response_deserializer=resource_dot_buffer__pb2.BufferCreateResponse.FromString,
                _registered_method=True)
        self.CreateBufferMultiple = channel.unary_unary(
                '/buffer.BufferService/CreateBufferMultiple',
                request_serializer=resource_dot_buffer__pb2.BufferMultipleSchema.SerializeToString,
                response_deserializer=resource_dot_buffer__pb2.BufferCreateMultipleResponse.FromString,
                _registered_method=True)
        self.UpdateBuffer = channel.unary_unary(
                '/buffer.BufferService/UpdateBuffer',
                request_serializer=resource_dot_buffer__pb2.BufferUpdate.SerializeToString,
                response_deserializer=resource_dot_buffer__pb2.BufferChangeResponse.FromString,
                _registered_method=True)
        self.UpdateBufferByTime = channel.unary_unary(
                '/buffer.BufferService/UpdateBufferByTime',
                request_serializer=resource_dot_buffer__pb2.BufferUpdateTime.SerializeToString,
                response_deserializer=resource_dot_buffer__pb2.BufferChangeResponse.FromString,
                _registered_method=True)
        self.DeleteBuffer = channel.unary_unary(
                '/buffer.BufferService/DeleteBuffer',
                request_serializer=resource_dot_buffer__pb2.BufferId.SerializeToString,
                response_deserializer=resource_dot_buffer__pb2.BufferChangeResponse.FromString,
                _registered_method=True)
        self.DeleteBufferByTime = channel.unary_unary(
                '/buffer.BufferService/DeleteBufferByTime',
                request_serializer=resource_dot_buffer__pb2.BufferTime.SerializeToString,
                response_deserializer=resource_dot_buffer__pb2.BufferChangeResponse.FromString,
                _registered_method=True)
        self.ReadBufferTimestamp = channel.unary_unary(
                '/buffer.BufferService/ReadBufferTimestamp',
                request_serializer=resource_dot_buffer__pb2.BufferTime.SerializeToString,
                response_deserializer=resource_dot_buffer__pb2.TimestampReadResponse.FromString,
                _registered_method=True)
        self.ListBufferTimestampByLatest = channel.unary_unary(
                '/buffer.BufferService/ListBufferTimestampByLatest',
                request_serializer=resource_dot_buffer__pb2.BufferLatest.SerializeToString,
                response_deserializer=resource_dot_buffer__pb2.TimestampListResponse.FromString,
                _registered_method=True)
        self.ListBufferTimestampByRange = channel.unary_unary(
                '/buffer.BufferService/ListBufferTimestampByRange',
                request_serializer=resource_dot_buffer__pb2.BufferRange.SerializeToString,
                response_deserializer=resource_dot_buffer__pb2.TimestampListResponse.FromString,
                _registered_method=True)
        self.ListBufferTimestampFirst = channel.unary_unary(
                '/buffer.BufferService/ListBufferTimestampFirst',
                request_serializer=resource_dot_buffer__pb2.BuffersSelector.SerializeToString,
                response_deserializer=resource_dot_buffer__pb2.TimestampListResponse.FromString,
                _registered_method=True)
        self.ListBufferTimestampLast = channel.unary_unary(
                '/buffer.BufferService/ListBufferTimestampLast',
                request_serializer=resource_dot_buffer__pb2.BuffersSelector.SerializeToString,
                response_deserializer=resource_dot_buffer__pb2.TimestampListResponse.FromString,
                _registered_method=True)
        self.ReadBufferGroupTimestamp = channel.unary_unary(
                '/buffer.BufferService/ReadBufferGroupTimestamp',
                request_serializer=resource_dot_buffer__pb2.BufferGroupTime.SerializeToString,
                response_deserializer=resource_dot_buffer__pb2.TimestampReadResponse.FromString,
                _registered_method=True)
        self.ListBufferGroupTimestampByLatest = channel.unary_unary(
                '/buffer.BufferService/ListBufferGroupTimestampByLatest',
                request_serializer=resource_dot_buffer__pb2.BufferGroupLatest.SerializeToString,
                response_deserializer=resource_dot_buffer__pb2.TimestampListResponse.FromString,
                _registered_method=True)
        self.ListBufferGroupTimestampByRange = channel.unary_unary(
                '/buffer.BufferService/ListBufferGroupTimestampByRange',
                request_serializer=resource_dot_buffer__pb2.BufferGroupRange.SerializeToString,
                response_deserializer=resource_dot_buffer__pb2.TimestampListResponse.FromString,
                _registered_method=True)
        self.ListBufferGroupTimestampFirst = channel.unary_unary(
                '/buffer.BufferService/ListBufferGroupTimestampFirst',
                request_serializer=resource_dot_buffer__pb2.BuffersGroupSelector.SerializeToString,
                response_deserializer=resource_dot_buffer__pb2.TimestampListResponse.FromString,
                _registered_method=True)
        self.ListBufferGroupTimestampLast = channel.unary_unary(
                '/buffer.BufferService/ListBufferGroupTimestampLast',
                request_serializer=resource_dot_buffer__pb2.BuffersGroupSelector.SerializeToString,
                response_deserializer=resource_dot_buffer__pb2.TimestampListResponse.FromString,
                _registered_method=True)
        self.CountBuffer = channel.unary_unary(
                '/buffer.BufferService/CountBuffer',
                request_serializer=resource_dot_buffer__pb2.BufferTime.SerializeToString,
                response_deserializer=resource_dot_buffer__pb2.BufferCountResponse.FromString,
                _registered_method=True)
        self.CountBufferByLatest = channel.unary_unary(
                '/buffer.BufferService/CountBufferByLatest',
                request_serializer=resource_dot_buffer__pb2.BufferLatest.SerializeToString,
                response_deserializer=resource_dot_buffer__pb2.BufferCountResponse.FromString,
                _registered_method=True)
        self.CountBufferByRange = channel.unary_unary(
                '/buffer.BufferService/CountBufferByRange',
                request_serializer=resource_dot_buffer__pb2.BufferRange.SerializeToString,
                response_deserializer=resource_dot_buffer__pb2.BufferCountResponse.FromString,
                _registered_method=True)
        self.CountBufferGroup = channel.unary_unary(
                '/buffer.BufferService/CountBufferGroup',
                request_serializer=resource_dot_buffer__pb2.BufferGroupTime.SerializeToString,
                response_deserializer=resource_dot_buffer__pb2.BufferCountResponse.FromString,
                _registered_method=True)
        self.CountBufferGroupByLatest = channel.unary_unary(
                '/buffer.BufferService/CountBufferGroupByLatest',
                request_serializer=resource_dot_buffer__pb2.BufferGroupLatest.SerializeToString,
                response_deserializer=resource_dot_buffer__pb2.BufferCountResponse.FromString,
                _registered_method=True)
        self.CountBufferGroupByRange = channel.unary_unary(
                '/buffer.BufferService/CountBufferGroupByRange',
                request_serializer=resource_dot_buffer__pb2.BufferGroupRange.SerializeToString,
                response_deserializer=resource_dot_buffer__pb2.BufferCountResponse.FromString,
                _registered_method=True)


class BufferServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReadBuffer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadBufferByTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBufferByIds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBufferByTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBufferByLatest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBufferByRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBufferByNumberBefore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBufferByNumberAfter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadBufferFirst(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadBufferLast(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBufferFirst(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBufferFirstOffset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBufferLast(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBufferLastOffset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBufferGroupByTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBufferGroupByLatest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBufferGroupByRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBufferGroupByNumberBefore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBufferGroupByNumberAfter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadBufferGroupFirst(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadBufferGroupLast(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBufferGroupFirst(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBufferGroupFirstOffset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBufferGroupLast(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBufferGroupLastOffset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadBufferSet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBufferSetByTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBufferSetByLatest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBufferSetByRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBuffer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBufferMultiple(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBuffer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBufferByTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBuffer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBufferByTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadBufferTimestamp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBufferTimestampByLatest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBufferTimestampByRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBufferTimestampFirst(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBufferTimestampLast(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadBufferGroupTimestamp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBufferGroupTimestampByLatest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBufferGroupTimestampByRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBufferGroupTimestampFirst(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBufferGroupTimestampLast(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CountBuffer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CountBufferByLatest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CountBufferByRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CountBufferGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CountBufferGroupByLatest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CountBufferGroupByRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BufferServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReadBuffer': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadBuffer,
                    request_deserializer=resource_dot_buffer__pb2.BufferId.FromString,
                    response_serializer=resource_dot_buffer__pb2.BufferReadResponse.SerializeToString,
            ),
            'ReadBufferByTime': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadBufferByTime,
                    request_deserializer=resource_dot_buffer__pb2.BufferTime.FromString,
                    response_serializer=resource_dot_buffer__pb2.BufferReadResponse.SerializeToString,
            ),
            'ListBufferByIds': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBufferByIds,
                    request_deserializer=resource_dot_buffer__pb2.BufferIds.FromString,
                    response_serializer=resource_dot_buffer__pb2.BufferListResponse.SerializeToString,
            ),
            'ListBufferByTime': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBufferByTime,
                    request_deserializer=resource_dot_buffer__pb2.BufferTime.FromString,
                    response_serializer=resource_dot_buffer__pb2.BufferListResponse.SerializeToString,
            ),
            'ListBufferByLatest': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBufferByLatest,
                    request_deserializer=resource_dot_buffer__pb2.BufferLatest.FromString,
                    response_serializer=resource_dot_buffer__pb2.BufferListResponse.SerializeToString,
            ),
            'ListBufferByRange': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBufferByRange,
                    request_deserializer=resource_dot_buffer__pb2.BufferRange.FromString,
                    response_serializer=resource_dot_buffer__pb2.BufferListResponse.SerializeToString,
            ),
            'ListBufferByNumberBefore': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBufferByNumberBefore,
                    request_deserializer=resource_dot_buffer__pb2.BufferNumber.FromString,
                    response_serializer=resource_dot_buffer__pb2.BufferListResponse.SerializeToString,
            ),
            'ListBufferByNumberAfter': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBufferByNumberAfter,
                    request_deserializer=resource_dot_buffer__pb2.BufferNumber.FromString,
                    response_serializer=resource_dot_buffer__pb2.BufferListResponse.SerializeToString,
            ),
            'ReadBufferFirst': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadBufferFirst,
                    request_deserializer=resource_dot_buffer__pb2.BufferSelector.FromString,
                    response_serializer=resource_dot_buffer__pb2.BufferReadResponse.SerializeToString,
            ),
            'ReadBufferLast': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadBufferLast,
                    request_deserializer=resource_dot_buffer__pb2.BufferSelector.FromString,
                    response_serializer=resource_dot_buffer__pb2.BufferReadResponse.SerializeToString,
            ),
            'ListBufferFirst': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBufferFirst,
                    request_deserializer=resource_dot_buffer__pb2.BuffersSelector.FromString,
                    response_serializer=resource_dot_buffer__pb2.BufferListResponse.SerializeToString,
            ),
            'ListBufferFirstOffset': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBufferFirstOffset,
                    request_deserializer=resource_dot_buffer__pb2.BuffersSelector.FromString,
                    response_serializer=resource_dot_buffer__pb2.BufferListResponse.SerializeToString,
            ),
            'ListBufferLast': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBufferLast,
                    request_deserializer=resource_dot_buffer__pb2.BuffersSelector.FromString,
                    response_serializer=resource_dot_buffer__pb2.BufferListResponse.SerializeToString,
            ),
            'ListBufferLastOffset': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBufferLastOffset,
                    request_deserializer=resource_dot_buffer__pb2.BuffersSelector.FromString,
                    response_serializer=resource_dot_buffer__pb2.BufferListResponse.SerializeToString,
            ),
            'ListBufferGroupByTime': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBufferGroupByTime,
                    request_deserializer=resource_dot_buffer__pb2.BufferGroupTime.FromString,
                    response_serializer=resource_dot_buffer__pb2.BufferListResponse.SerializeToString,
            ),
            'ListBufferGroupByLatest': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBufferGroupByLatest,
                    request_deserializer=resource_dot_buffer__pb2.BufferGroupLatest.FromString,
                    response_serializer=resource_dot_buffer__pb2.BufferListResponse.SerializeToString,
            ),
            'ListBufferGroupByRange': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBufferGroupByRange,
                    request_deserializer=resource_dot_buffer__pb2.BufferGroupRange.FromString,
                    response_serializer=resource_dot_buffer__pb2.BufferListResponse.SerializeToString,
            ),
            'ListBufferGroupByNumberBefore': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBufferGroupByNumberBefore,
                    request_deserializer=resource_dot_buffer__pb2.BufferGroupNumber.FromString,
                    response_serializer=resource_dot_buffer__pb2.BufferListResponse.SerializeToString,
            ),
            'ListBufferGroupByNumberAfter': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBufferGroupByNumberAfter,
                    request_deserializer=resource_dot_buffer__pb2.BufferGroupNumber.FromString,
                    response_serializer=resource_dot_buffer__pb2.BufferListResponse.SerializeToString,
            ),
            'ReadBufferGroupFirst': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadBufferGroupFirst,
                    request_deserializer=resource_dot_buffer__pb2.BufferGroupSelector.FromString,
                    response_serializer=resource_dot_buffer__pb2.BufferReadResponse.SerializeToString,
            ),
            'ReadBufferGroupLast': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadBufferGroupLast,
                    request_deserializer=resource_dot_buffer__pb2.BufferGroupSelector.FromString,
                    response_serializer=resource_dot_buffer__pb2.BufferReadResponse.SerializeToString,
            ),
            'ListBufferGroupFirst': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBufferGroupFirst,
                    request_deserializer=resource_dot_buffer__pb2.BuffersGroupSelector.FromString,
                    response_serializer=resource_dot_buffer__pb2.BufferListResponse.SerializeToString,
            ),
            'ListBufferGroupFirstOffset': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBufferGroupFirstOffset,
                    request_deserializer=resource_dot_buffer__pb2.BuffersGroupSelector.FromString,
                    response_serializer=resource_dot_buffer__pb2.BufferListResponse.SerializeToString,
            ),
            'ListBufferGroupLast': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBufferGroupLast,
                    request_deserializer=resource_dot_buffer__pb2.BuffersGroupSelector.FromString,
                    response_serializer=resource_dot_buffer__pb2.BufferListResponse.SerializeToString,
            ),
            'ListBufferGroupLastOffset': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBufferGroupLastOffset,
                    request_deserializer=resource_dot_buffer__pb2.BuffersGroupSelector.FromString,
                    response_serializer=resource_dot_buffer__pb2.BufferListResponse.SerializeToString,
            ),
            'ReadBufferSet': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadBufferSet,
                    request_deserializer=resource_dot_buffer__pb2.BufferSetTime.FromString,
                    response_serializer=resource_dot_buffer__pb2.BufferSetReadResponse.SerializeToString,
            ),
            'ListBufferSetByTime': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBufferSetByTime,
                    request_deserializer=resource_dot_buffer__pb2.BufferSetTime.FromString,
                    response_serializer=resource_dot_buffer__pb2.BufferSetListResponse.SerializeToString,
            ),
            'ListBufferSetByLatest': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBufferSetByLatest,
                    request_deserializer=resource_dot_buffer__pb2.BufferSetLatest.FromString,
                    response_serializer=resource_dot_buffer__pb2.BufferSetListResponse.SerializeToString,
            ),
            'ListBufferSetByRange': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBufferSetByRange,
                    request_deserializer=resource_dot_buffer__pb2.BufferSetRange.FromString,
                    response_serializer=resource_dot_buffer__pb2.BufferSetListResponse.SerializeToString,
            ),
            'CreateBuffer': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBuffer,
                    request_deserializer=resource_dot_buffer__pb2.BufferSchema.FromString,
                    response_serializer=resource_dot_buffer__pb2.BufferCreateResponse.SerializeToString,
            ),
            'CreateBufferMultiple': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBufferMultiple,
                    request_deserializer=resource_dot_buffer__pb2.BufferMultipleSchema.FromString,
                    response_serializer=resource_dot_buffer__pb2.BufferCreateMultipleResponse.SerializeToString,
            ),
            'UpdateBuffer': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBuffer,
                    request_deserializer=resource_dot_buffer__pb2.BufferUpdate.FromString,
                    response_serializer=resource_dot_buffer__pb2.BufferChangeResponse.SerializeToString,
            ),
            'UpdateBufferByTime': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBufferByTime,
                    request_deserializer=resource_dot_buffer__pb2.BufferUpdateTime.FromString,
                    response_serializer=resource_dot_buffer__pb2.BufferChangeResponse.SerializeToString,
            ),
            'DeleteBuffer': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBuffer,
                    request_deserializer=resource_dot_buffer__pb2.BufferId.FromString,
                    response_serializer=resource_dot_buffer__pb2.BufferChangeResponse.SerializeToString,
            ),
            'DeleteBufferByTime': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBufferByTime,
                    request_deserializer=resource_dot_buffer__pb2.BufferTime.FromString,
                    response_serializer=resource_dot_buffer__pb2.BufferChangeResponse.SerializeToString,
            ),
            'ReadBufferTimestamp': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadBufferTimestamp,
                    request_deserializer=resource_dot_buffer__pb2.BufferTime.FromString,
                    response_serializer=resource_dot_buffer__pb2.TimestampReadResponse.SerializeToString,
            ),
            'ListBufferTimestampByLatest': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBufferTimestampByLatest,
                    request_deserializer=resource_dot_buffer__pb2.BufferLatest.FromString,
                    response_serializer=resource_dot_buffer__pb2.TimestampListResponse.SerializeToString,
            ),
            'ListBufferTimestampByRange': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBufferTimestampByRange,
                    request_deserializer=resource_dot_buffer__pb2.BufferRange.FromString,
                    response_serializer=resource_dot_buffer__pb2.TimestampListResponse.SerializeToString,
            ),
            'ListBufferTimestampFirst': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBufferTimestampFirst,
                    request_deserializer=resource_dot_buffer__pb2.BuffersSelector.FromString,
                    response_serializer=resource_dot_buffer__pb2.TimestampListResponse.SerializeToString,
            ),
            'ListBufferTimestampLast': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBufferTimestampLast,
                    request_deserializer=resource_dot_buffer__pb2.BuffersSelector.FromString,
                    response_serializer=resource_dot_buffer__pb2.TimestampListResponse.SerializeToString,
            ),
            'ReadBufferGroupTimestamp': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadBufferGroupTimestamp,
                    request_deserializer=resource_dot_buffer__pb2.BufferGroupTime.FromString,
                    response_serializer=resource_dot_buffer__pb2.TimestampReadResponse.SerializeToString,
            ),
            'ListBufferGroupTimestampByLatest': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBufferGroupTimestampByLatest,
                    request_deserializer=resource_dot_buffer__pb2.BufferGroupLatest.FromString,
                    response_serializer=resource_dot_buffer__pb2.TimestampListResponse.SerializeToString,
            ),
            'ListBufferGroupTimestampByRange': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBufferGroupTimestampByRange,
                    request_deserializer=resource_dot_buffer__pb2.BufferGroupRange.FromString,
                    response_serializer=resource_dot_buffer__pb2.TimestampListResponse.SerializeToString,
            ),
            'ListBufferGroupTimestampFirst': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBufferGroupTimestampFirst,
                    request_deserializer=resource_dot_buffer__pb2.BuffersGroupSelector.FromString,
                    response_serializer=resource_dot_buffer__pb2.TimestampListResponse.SerializeToString,
            ),
            'ListBufferGroupTimestampLast': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBufferGroupTimestampLast,
                    request_deserializer=resource_dot_buffer__pb2.BuffersGroupSelector.FromString,
                    response_serializer=resource_dot_buffer__pb2.TimestampListResponse.SerializeToString,
            ),
            'CountBuffer': grpc.unary_unary_rpc_method_handler(
                    servicer.CountBuffer,
                    request_deserializer=resource_dot_buffer__pb2.BufferTime.FromString,
                    response_serializer=resource_dot_buffer__pb2.BufferCountResponse.SerializeToString,
            ),
            'CountBufferByLatest': grpc.unary_unary_rpc_method_handler(
                    servicer.CountBufferByLatest,
                    request_deserializer=resource_dot_buffer__pb2.BufferLatest.FromString,
                    response_serializer=resource_dot_buffer__pb2.BufferCountResponse.SerializeToString,
            ),
            'CountBufferByRange': grpc.unary_unary_rpc_method_handler(
                    servicer.CountBufferByRange,
                    request_deserializer=resource_dot_buffer__pb2.BufferRange.FromString,
                    response_serializer=resource_dot_buffer__pb2.BufferCountResponse.SerializeToString,
            ),
            'CountBufferGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.CountBufferGroup,
                    request_deserializer=resource_dot_buffer__pb2.BufferGroupTime.FromString,
                    response_serializer=resource_dot_buffer__pb2.BufferCountResponse.SerializeToString,
            ),
            'CountBufferGroupByLatest': grpc.unary_unary_rpc_method_handler(
                    servicer.CountBufferGroupByLatest,
                    request_deserializer=resource_dot_buffer__pb2.BufferGroupLatest.FromString,
                    response_serializer=resource_dot_buffer__pb2.BufferCountResponse.SerializeToString,
            ),
            'CountBufferGroupByRange': grpc.unary_unary_rpc_method_handler(
                    servicer.CountBufferGroupByRange,
                    request_deserializer=resource_dot_buffer__pb2.BufferGroupRange.FromString,
                    response_serializer=resource_dot_buffer__pb2.BufferCountResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'buffer.BufferService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('buffer.BufferService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BufferService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReadBuffer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/ReadBuffer',
            resource_dot_buffer__pb2.BufferId.SerializeToString,
            resource_dot_buffer__pb2.BufferReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadBufferByTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/ReadBufferByTime',
            resource_dot_buffer__pb2.BufferTime.SerializeToString,
            resource_dot_buffer__pb2.BufferReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBufferByIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/ListBufferByIds',
            resource_dot_buffer__pb2.BufferIds.SerializeToString,
            resource_dot_buffer__pb2.BufferListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBufferByTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/ListBufferByTime',
            resource_dot_buffer__pb2.BufferTime.SerializeToString,
            resource_dot_buffer__pb2.BufferListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBufferByLatest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/ListBufferByLatest',
            resource_dot_buffer__pb2.BufferLatest.SerializeToString,
            resource_dot_buffer__pb2.BufferListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBufferByRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/ListBufferByRange',
            resource_dot_buffer__pb2.BufferRange.SerializeToString,
            resource_dot_buffer__pb2.BufferListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBufferByNumberBefore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/ListBufferByNumberBefore',
            resource_dot_buffer__pb2.BufferNumber.SerializeToString,
            resource_dot_buffer__pb2.BufferListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBufferByNumberAfter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/ListBufferByNumberAfter',
            resource_dot_buffer__pb2.BufferNumber.SerializeToString,
            resource_dot_buffer__pb2.BufferListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadBufferFirst(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/ReadBufferFirst',
            resource_dot_buffer__pb2.BufferSelector.SerializeToString,
            resource_dot_buffer__pb2.BufferReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadBufferLast(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/ReadBufferLast',
            resource_dot_buffer__pb2.BufferSelector.SerializeToString,
            resource_dot_buffer__pb2.BufferReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBufferFirst(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/ListBufferFirst',
            resource_dot_buffer__pb2.BuffersSelector.SerializeToString,
            resource_dot_buffer__pb2.BufferListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBufferFirstOffset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/ListBufferFirstOffset',
            resource_dot_buffer__pb2.BuffersSelector.SerializeToString,
            resource_dot_buffer__pb2.BufferListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBufferLast(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/ListBufferLast',
            resource_dot_buffer__pb2.BuffersSelector.SerializeToString,
            resource_dot_buffer__pb2.BufferListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBufferLastOffset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/ListBufferLastOffset',
            resource_dot_buffer__pb2.BuffersSelector.SerializeToString,
            resource_dot_buffer__pb2.BufferListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBufferGroupByTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/ListBufferGroupByTime',
            resource_dot_buffer__pb2.BufferGroupTime.SerializeToString,
            resource_dot_buffer__pb2.BufferListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBufferGroupByLatest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/ListBufferGroupByLatest',
            resource_dot_buffer__pb2.BufferGroupLatest.SerializeToString,
            resource_dot_buffer__pb2.BufferListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBufferGroupByRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/ListBufferGroupByRange',
            resource_dot_buffer__pb2.BufferGroupRange.SerializeToString,
            resource_dot_buffer__pb2.BufferListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBufferGroupByNumberBefore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/ListBufferGroupByNumberBefore',
            resource_dot_buffer__pb2.BufferGroupNumber.SerializeToString,
            resource_dot_buffer__pb2.BufferListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBufferGroupByNumberAfter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/ListBufferGroupByNumberAfter',
            resource_dot_buffer__pb2.BufferGroupNumber.SerializeToString,
            resource_dot_buffer__pb2.BufferListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadBufferGroupFirst(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/ReadBufferGroupFirst',
            resource_dot_buffer__pb2.BufferGroupSelector.SerializeToString,
            resource_dot_buffer__pb2.BufferReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadBufferGroupLast(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/ReadBufferGroupLast',
            resource_dot_buffer__pb2.BufferGroupSelector.SerializeToString,
            resource_dot_buffer__pb2.BufferReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBufferGroupFirst(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/ListBufferGroupFirst',
            resource_dot_buffer__pb2.BuffersGroupSelector.SerializeToString,
            resource_dot_buffer__pb2.BufferListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBufferGroupFirstOffset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/ListBufferGroupFirstOffset',
            resource_dot_buffer__pb2.BuffersGroupSelector.SerializeToString,
            resource_dot_buffer__pb2.BufferListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBufferGroupLast(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/ListBufferGroupLast',
            resource_dot_buffer__pb2.BuffersGroupSelector.SerializeToString,
            resource_dot_buffer__pb2.BufferListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBufferGroupLastOffset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/ListBufferGroupLastOffset',
            resource_dot_buffer__pb2.BuffersGroupSelector.SerializeToString,
            resource_dot_buffer__pb2.BufferListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadBufferSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/ReadBufferSet',
            resource_dot_buffer__pb2.BufferSetTime.SerializeToString,
            resource_dot_buffer__pb2.BufferSetReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBufferSetByTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/ListBufferSetByTime',
            resource_dot_buffer__pb2.BufferSetTime.SerializeToString,
            resource_dot_buffer__pb2.BufferSetListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBufferSetByLatest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/ListBufferSetByLatest',
            resource_dot_buffer__pb2.BufferSetLatest.SerializeToString,
            resource_dot_buffer__pb2.BufferSetListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBufferSetByRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/ListBufferSetByRange',
            resource_dot_buffer__pb2.BufferSetRange.SerializeToString,
            resource_dot_buffer__pb2.BufferSetListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateBuffer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/CreateBuffer',
            resource_dot_buffer__pb2.BufferSchema.SerializeToString,
            resource_dot_buffer__pb2.BufferCreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateBufferMultiple(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/CreateBufferMultiple',
            resource_dot_buffer__pb2.BufferMultipleSchema.SerializeToString,
            resource_dot_buffer__pb2.BufferCreateMultipleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateBuffer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/UpdateBuffer',
            resource_dot_buffer__pb2.BufferUpdate.SerializeToString,
            resource_dot_buffer__pb2.BufferChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateBufferByTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/UpdateBufferByTime',
            resource_dot_buffer__pb2.BufferUpdateTime.SerializeToString,
            resource_dot_buffer__pb2.BufferChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteBuffer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/DeleteBuffer',
            resource_dot_buffer__pb2.BufferId.SerializeToString,
            resource_dot_buffer__pb2.BufferChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteBufferByTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/DeleteBufferByTime',
            resource_dot_buffer__pb2.BufferTime.SerializeToString,
            resource_dot_buffer__pb2.BufferChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadBufferTimestamp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/ReadBufferTimestamp',
            resource_dot_buffer__pb2.BufferTime.SerializeToString,
            resource_dot_buffer__pb2.TimestampReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBufferTimestampByLatest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/ListBufferTimestampByLatest',
            resource_dot_buffer__pb2.BufferLatest.SerializeToString,
            resource_dot_buffer__pb2.TimestampListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBufferTimestampByRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/ListBufferTimestampByRange',
            resource_dot_buffer__pb2.BufferRange.SerializeToString,
            resource_dot_buffer__pb2.TimestampListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBufferTimestampFirst(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/ListBufferTimestampFirst',
            resource_dot_buffer__pb2.BuffersSelector.SerializeToString,
            resource_dot_buffer__pb2.TimestampListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBufferTimestampLast(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/ListBufferTimestampLast',
            resource_dot_buffer__pb2.BuffersSelector.SerializeToString,
            resource_dot_buffer__pb2.TimestampListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadBufferGroupTimestamp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/ReadBufferGroupTimestamp',
            resource_dot_buffer__pb2.BufferGroupTime.SerializeToString,
            resource_dot_buffer__pb2.TimestampReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBufferGroupTimestampByLatest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/ListBufferGroupTimestampByLatest',
            resource_dot_buffer__pb2.BufferGroupLatest.SerializeToString,
            resource_dot_buffer__pb2.TimestampListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBufferGroupTimestampByRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/ListBufferGroupTimestampByRange',
            resource_dot_buffer__pb2.BufferGroupRange.SerializeToString,
            resource_dot_buffer__pb2.TimestampListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBufferGroupTimestampFirst(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/ListBufferGroupTimestampFirst',
            resource_dot_buffer__pb2.BuffersGroupSelector.SerializeToString,
            resource_dot_buffer__pb2.TimestampListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBufferGroupTimestampLast(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/ListBufferGroupTimestampLast',
            resource_dot_buffer__pb2.BuffersGroupSelector.SerializeToString,
            resource_dot_buffer__pb2.TimestampListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CountBuffer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/CountBuffer',
            resource_dot_buffer__pb2.BufferTime.SerializeToString,
            resource_dot_buffer__pb2.BufferCountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CountBufferByLatest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/CountBufferByLatest',
            resource_dot_buffer__pb2.BufferLatest.SerializeToString,
            resource_dot_buffer__pb2.BufferCountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CountBufferByRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/CountBufferByRange',
            resource_dot_buffer__pb2.BufferRange.SerializeToString,
            resource_dot_buffer__pb2.BufferCountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CountBufferGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/CountBufferGroup',
            resource_dot_buffer__pb2.BufferGroupTime.SerializeToString,
            resource_dot_buffer__pb2.BufferCountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CountBufferGroupByLatest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/CountBufferGroupByLatest',
            resource_dot_buffer__pb2.BufferGroupLatest.SerializeToString,
            resource_dot_buffer__pb2.BufferCountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CountBufferGroupByRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/CountBufferGroupByRange',
            resource_dot_buffer__pb2.BufferGroupRange.SerializeToString,
            resource_dot_buffer__pb2.BufferCountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
