/**
 * @fileoverview gRPC-Web generated client stub for config
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.2
// 	protoc              v6.33.1
// source: resource/config.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.config = require('./config_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.config.ConfigServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.config.ConfigServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.config.ApiIdRequest,
 *   !proto.config.ApiIdResponse>}
 */
const methodDescriptor_ConfigService_ApiId = new grpc.web.MethodDescriptor(
  '/config.ConfigService/ApiId',
  grpc.web.MethodType.UNARY,
  proto.config.ApiIdRequest,
  proto.config.ApiIdResponse,
  /**
   * @param {!proto.config.ApiIdRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.config.ApiIdResponse.deserializeBinary
);


/**
 * @param {!proto.config.ApiIdRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.config.ApiIdResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.config.ApiIdResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.config.ConfigServiceClient.prototype.apiId =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/config.ConfigService/ApiId',
      request,
      metadata || {},
      methodDescriptor_ConfigService_ApiId,
      callback);
};


/**
 * @param {!proto.config.ApiIdRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.config.ApiIdResponse>}
 *     Promise that resolves to the response
 */
proto.config.ConfigServicePromiseClient.prototype.apiId =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/config.ConfigService/ApiId',
      request,
      metadata || {},
      methodDescriptor_ConfigService_ApiId);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.config.AccessRequest,
 *   !proto.config.ProcedureAccesResponse>}
 */
const methodDescriptor_ConfigService_ProcedureAccess = new grpc.web.MethodDescriptor(
  '/config.ConfigService/ProcedureAccess',
  grpc.web.MethodType.UNARY,
  proto.config.AccessRequest,
  proto.config.ProcedureAccesResponse,
  /**
   * @param {!proto.config.AccessRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.config.ProcedureAccesResponse.deserializeBinary
);


/**
 * @param {!proto.config.AccessRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.config.ProcedureAccesResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.config.ProcedureAccesResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.config.ConfigServiceClient.prototype.procedureAccess =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/config.ConfigService/ProcedureAccess',
      request,
      metadata || {},
      methodDescriptor_ConfigService_ProcedureAccess,
      callback);
};


/**
 * @param {!proto.config.AccessRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.config.ProcedureAccesResponse>}
 *     Promise that resolves to the response
 */
proto.config.ConfigServicePromiseClient.prototype.procedureAccess =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/config.ConfigService/ProcedureAccess',
      request,
      metadata || {},
      methodDescriptor_ConfigService_ProcedureAccess);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.config.AccessRequest,
 *   !proto.config.RoleAccesResponse>}
 */
const methodDescriptor_ConfigService_RoleAccess = new grpc.web.MethodDescriptor(
  '/config.ConfigService/RoleAccess',
  grpc.web.MethodType.UNARY,
  proto.config.AccessRequest,
  proto.config.RoleAccesResponse,
  /**
   * @param {!proto.config.AccessRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.config.RoleAccesResponse.deserializeBinary
);


/**
 * @param {!proto.config.AccessRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.config.RoleAccesResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.config.RoleAccesResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.config.ConfigServiceClient.prototype.roleAccess =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/config.ConfigService/RoleAccess',
      request,
      metadata || {},
      methodDescriptor_ConfigService_RoleAccess,
      callback);
};


/**
 * @param {!proto.config.AccessRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.config.RoleAccesResponse>}
 *     Promise that resolves to the response
 */
proto.config.ConfigServicePromiseClient.prototype.roleAccess =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/config.ConfigService/RoleAccess',
      request,
      metadata || {},
      methodDescriptor_ConfigService_RoleAccess);
};


module.exports = proto.config;

